# NumPy Essentials Practice Exercises Overview:
Time to test the knowledge on NumPy. Lets start with simple task and move on to more challenging ones!<br>
**Good Luck**<br>

&#9758; *Please note, there are several ways to get the required output, so your code could be different then what is provided in this notebook. <br>As long as you are getting the tasks done, it is fine at this stage. *

**1. How to import `NumPy` library?** 

In [2]:
# To avoid overwriting the output, please code here 

In [27]:
import numpy as np

**2. Convert the given Python list into NumPy array and check its data type**

In [28]:
list_1 = [1,2,3,4,5]

In [12]:
# To avoid overwriting the output, please code here 

In [19]:
# To avoid overwriting the output, please code here 

In [38]:
arr= np.array(list_1)
arr ,type(arr)

(array([1, 2, 3, 4, 5]), numpy.ndarray)

**3. Generate `array [0,1,2,3,4,5]` using NumPy built-in function, `arange()`**

In [41]:
np.arange(0,6,1)

array([0, 1, 2, 3, 4, 5])

**4. Generate an `array of "5" zeros`**

In [22]:
# To avoid overwriting the output, please code here 

In [43]:
array = np.zeros(5)
array

array([0., 0., 0., 0., 0.])

**5. Generate the following `matrix`.**

In [11]:
# To avoid overwriting the output, please code here 

In [46]:
array = np.zeros((3,4))
array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

**6. Generate** `[1.,1.,1.,1.,1.]` **using NumPy built-in function?**

In [13]:
# To avoid overwriting the output, please code here 

In [48]:
np.ones([1,5])

array([[1., 1., 1., 1., 1.]])

**7. Generate an array of "5" tens.**

In [15]:
# To avoid overwriting the output, please code here 

In [50]:
np.ones(5)*10

array([10., 10., 10., 10., 10.])

**8. Use `arange()` to generate an array of even numbers between 50 and 100.**<br>
*50 and 100 are not included*

In [17]:
# To avoid overwriting the output, please code here 

In [52]:
np.arange(52,100,2)

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

**9. Generate an array of 10 linearly spaced points between 0 and 1.**<br>
**Output step size as well?**

In [19]:
# To avoid overwriting the output, please code here 

In [61]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

**10. Perform the following tasks:**
* Generate a **`vector array of 25`** numbers using **`arange()`**
* write a code to convert the vector array into **`2-D matrix using reshape`**
* can we use **`shape`** instead of reshape as well?

In [21]:
# To avoid overwriting the output, please code here 

In [62]:
# Generating vector array
np.arange(0,25,1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
# To avoid overwriting the output, please code here 

In [63]:
# reshape to convert into 2-d
a= np.arange(25).reshape((5,5))

In [25]:
# To avoid overwriting the output, please code here 

In [26]:
# Using shape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**11. How to generate a single random number using NumPy built-in function?**

In [67]:
# To avoid overwriting the output, please code here 
#from numpy import random

In [75]:
np.random.rand(1)

array([0.43779277])

**12. Write a code to generate a 7x5 matrix of 35 random numbers?** <br>
*Notice, there are no ( ) in the output matrix!*

In [34]:
# To avoid overwriting the output, please code here 

In [76]:
np.random.rand(7,5)

array([[0.28549656, 0.92262642, 0.88535664, 0.20435681, 0.52232657],
       [0.14384591, 0.97174058, 0.62556571, 0.65657715, 0.57352693],
       [0.14106291, 0.02856107, 0.65242763, 0.67188125, 0.31464786],
       [0.15631552, 0.70727602, 0.91081726, 0.20784315, 0.27777228],
       [0.63943749, 0.3687082 , 0.95105084, 0.57240905, 0.6729263 ],
       [0.98957186, 0.46431787, 0.8172172 , 0.07852529, 0.23791715],
       [0.37212155, 0.33900884, 0.66248086, 0.31800566, 0.95781379]])

**13. Generate the following matrix using NumPy's built-in method for identity matrix.**

In [36]:
# To avoid overwriting the output, please code here 

In [81]:
np.identity(5)*5

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

**14. Generate the follow matrix "array_2d" and replicate the provided outputs.**

In [91]:
#18a:
# To avoid overwriting the output, please code here 
array = np.arange(30).reshape(6,5)




In [92]:
b=np.copy(array)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

**15. Can you calculate the sum of all the numbers in array_2d?**

In [50]:
# To avoid overwriting the output, please code here 

In [95]:
array = np.arange(30).reshape(6,5)
np.sum(array)

435

**16. Calculate sum of all the rows and columns in array_2d.**

In [52]:
# To avoid overwriting the output, please code here 

In [97]:
arr1 = np.arange(30).reshape(6,5)
column_sum = arr1.sum(axis = 0)
print("comumn sum:",column_sum)
row_sum = arr1.sum(axis = 1)
print("row sum:",row_sum)


comumn sum: [75 81 87 93 99]
row sum: [ 10  35  60  85 110 135]


**17. Calculate the standard deviation of the values in array_2d.**

In [54]:
# To avoid overwriting the output, please code here 

In [99]:
array = np.arange(30).reshape(6,5)
np.std(array)

8.65544144839919

### You must be feeling comfortable using NumPy now!
# Great Job and Good Luck 